server:
  port: 8085

spring:
  security:
    oauth2:
      client:
        provider:
          api-gateway:
            issuer-uri: http://localhost:8080/realms/dh_demo
        registration:
          api-gateway:
            provider: api-gateway
            client-id: gateway-client
            client-secret: 45l7ceVPNFVDDT5dc9xgFde1nlFIOHMV
            scope: openid
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8085/login/oauth2/code/keycloak
  cloud:
    gateway:
      default-filters:
        - TokenRelay
      routes:
        - id: hello-service
          uri: http://localhost:8086
          predicates:
            - Path=/hello/**