server:
  port: 9090

spring:
  application:
    name: api-gateway
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: http://localhost:8080/realms/dh_feign
        registration:
          gateway-service:
            provider: keycloak
            client-id: gateway
            client-secret: Llhl0JrMGeHs8A3Gscwy66pjhfJGw5WI
            authorization-grant-type: authorization_code
            scope:
              - openid
            redirect-uri: 'http://localhost:9090/login/oauth2/code/keycloak'
  cloud:
    gateway:
      default-filters:
        - TokenRelay
      routes:
        - id: users-service
          uri: http://localhost:8086
          predicates:
            - Path=/users/**
          filters:
            - StripPrefix=0