server:
  port: 8082
  servlet:
    context-path: /api

spring:
  application:
    name: springboot-keycloak
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/spring_demo
          jwt-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect-certs

jwt:
  auth:
    converter:
      resource-id: spring-client
      principal-attribute: preferred_username

logging:
  level:
    org.springframework.security: DEBUG