server:
  port: 8086

spring:
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: http://localhost:8080/realms/dh_demo
        registration:
          keycloak:
            client-id: backend
            client-secret: kUydoN42hjRYitGUKtJDkkrTjhYkMMIu
            redirect-uri: http://localhost:8086/login/oauth2/code/google